<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>MorpheX</RootNamespace>
    <AssemblyName>MorpheX</AssemblyName>
    <ApplicationIcon>Assets\Branding\morphex-icon.ico</ApplicationIcon>
    <Description>Lightweight live wallpapers for Windows.</Description>
    <Company>MorpheusDark</Company>
    <Product>MorpheX Live</Product>
    <Version>0.1.34</Version>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>

    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <PublishReadyToRun>true</PublishReadyToRun>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <RetainVMGarbageCollection>false</RetainVMGarbageCollection>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <Target Name="RemoveUnusedLibVlcRuntimes" AfterTargets="Publish">
    <RemoveDir Directories="$(PublishDir)libvlc\win-arm64" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x86" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x64\lua" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x64\hrtfs" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x64\plugins\access_output" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x64\plugins\stream_out" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x64\plugins\mux" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x64\plugins\services_discovery" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x64\plugins\keystore" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x64\plugins\visualization" />
    <RemoveDir Directories="$(PublishDir)libvlc\win-x64\plugins\video_splitter" />
    <RemoveDir Directories="$(PublishDir)runtimes" />
    <Delete Files="$(PublishDir)libvlc\win-x64\*.lib" />
    <Delete Files="$(PublishDir)libvlc\win-x64\vlc-cache-gen.exe" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\libdcp_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\libaccess_srt_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\librist_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\liblibbluray_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\libcdda_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\libdtv_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\libsftp_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\*.jar" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\codec\libzvbi_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\codec\libgme_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\codec\libx26410b_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\codec\libaom_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\librtp_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\liblive555_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\libnfs_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\libvcd_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\libvdr_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\access\libsatip_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\video_filter\libpuzzle_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\video_filter\libball_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\video_filter\libpsychedelic_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\video_filter\libanaglyph_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\video_filter\libripple_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\audio_filter\libspatialaudio_plugin.dll" />
    <Delete Files="$(PublishDir)libvlc\win-x64\plugins\video_output\libcaca_plugin.dll" />
    <Delete Files="$(PublishDir)*.pdb" />
    <Delete Files="$(PublishDir)*.xml" />
    <Delete Files="$(PublishDir)WebView2Loader.dll" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\MorpheX.Core\MorpheX.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.*" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.*" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\**" />
    <Content Include="Assets\Fonts\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
